version: '3'

services:

  full-teaching-mysql:
    image: mysql:5.7.22
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=full_teaching

  full-teaching-openvidu-server-kms:
    image: openvidu/openvidu-server-kms:2.3.0 
    ports:
      - 4443:4443
    environment:
      - openvidu.secret=MY_SECRET
      - openvidu.publicurl=docker

  full-teaching:
    image: codeurjc/full-teaching:2.3.0
    depends_on:
      - full-teaching-mysql
      - full-teaching-openvidu-server-kms
    ports:
      - 5000:5000
    environment:
      - WAIT_HOSTS=full-teaching-mysql:3306
      - WAIT_HOSTS_TIMEOUT=60
      - MYSQL_PORT_3306_TCP_ADDR=full-teaching-mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_ENV_MYSQL_DATABASE=full_teaching
      - MYSQL_ENV_MYSQL_USER=root
      - MYSQL_ENV_MYSQL_PASSWORD=pass
      - server.port=5000
      - openvidu.url=https://full-teaching-openvidu-server-kms:4443
      - openvidu.secret=MY_SECRET