version: '3.3'
services:
  master:
    build: .
    image: elastest/etm-jenkins:1.0.3
    restart: unless-stopped
    hostname: jenkins
    ports:
      - "0.0.0.0:37092:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
networks:
  default:
    external:
      name: elastest_elastest
 